const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  DIRECTOR: "DIRECTOR",
  GERENTE: "GERENTE",
  AUDITOR: "AUDITOR",
  JEFATURA: "JEFATURA"
};

const ASSIGNABLE_ROLES = [
  ROLES.DIRECTOR,
  ROLES.GERENTE,
  ROLES.AUDITOR,
  ROLES.JEFATURA
];


const DEFAULT_ROLE = ROLES.JEFATURA;

// Roles que pueden administrar usuarios.
const USER_ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.DIRECTOR];

module.exports = { ROLES, ASSIGNABLE_ROLES, DEFAULT_ROLE, USER_ADMIN_ROLES };
