-- Run this script in the Supabase SQL Editor before enabling login logging.
-- Configure SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY for the backend only.
create table if not exists public.logins (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  username text not null,
  logged_in_at timestamptz not null default now(),
  ip_address inet,
  method text not null check (method in ('PASSWORD', 'PASSWORD_2FA'))
);

alter table public.logins enable row level security;
